version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
  working_directory: /home/circleci/project
    steps:
      - checkout
      - run: 
          name: ant TestUser -lib lib/ -buildfile build.xml
          command: ant TestUser -lib lib/ -buildfile build.xml
